services:
  thyrefrontend:
    build: .
    container_name: thyrefrontend
    restart: unless-stopped

    networks:
      - caddy

    # Not needed when Caddy is the public entrypoint.
    # Uncomment for local testing without Caddy:
    # ports:
    #   - "3000:3000"

    labels:
      # set this to the hostname you want
      caddy: thyre.co
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true